### ISSUE TITLE
ValueError: math domain error in compute_d_max: math.pow(region['n'] - region['s'], 2)) / 100

### ISSUE THREAD

**Issue by iboates** [ldesousa/r.mblend#11] opened 2018-03-31 11:23 UTC
I am trying to blend an oddly-shaped high-resolution raster with a square low resolution raster:

![image](https://user-images.githubusercontent.com/13814358/38162656-6b85829c-34e5-11e8-9ddc-09ac4c050117.png)

But I am getting this error:

```
r.mblend high=dtm2 low=aster2 output=result2                                    
Region:
{'rows': 5368, 'e': 321526.83037128, 'cells': 26018696, 'cols': 4847, 'n': 5380421.639, 's': 5377737.66126622, 'w': 319103.433, 'ewres': 0.49997883, 'nsres': 0.49999585}
Traceback (most recent call last):
  File "/home/isaac/.grass7/addons/scripts/r.mblend", line
279, in <module>
    main()
  File "/home/isaac/.grass7/addons/scripts/r.mblend", line
136, in main
    compute_d_max(region)
  File "/home/isaac/.grass7/addons/scripts/r.mblend", line
90, in compute_d_max
    math.pow(region['n'] - region['s'], 2)) / 100
ValueError: math domain error
```

I thought maybe it had to do with the `far_edge` parameter being set to high, but even changing it to `1` generates the same error:\
```
r.mblend high=dtm2 low=aster2 output=result2 far_edge=1                         
Region:
{'rows': 5368, 'e': 321526.83037128, 'cells': 26018696, 'cols': 4847, 'n': 5380421.639, 's': 5377737.66126622, 'w': 319103.433, 'ewres': 0.49997883, 'nsres': 0.49999585}
Traceback (most recent call last):
  File "/home/isaac/.grass7/addons/scripts/r.mblend", line
279, in <module>
    main()
  File "/home/isaac/.grass7/addons/scripts/r.mblend", line
136, in main
    compute_d_max(region)
  File "/home/isaac/.grass7/addons/scripts/r.mblend", line
90, in compute_d_max
    math.pow(region['n'] - region['s'], 2)) / 100
ValueError: math domain error
```

The minimum distance from the high-res raster's extent to the extent of the low raster is 100m. Maybe I am not understanding how the`far_edge` parameter is interpreted - it is apparently _Percentage of distance to high resolution raster used to determine far edge_ - percentage of distance from what? Why does it have to be a percentage? Wouldn't it be easier to just say "100m from the edge of the high-resolution raster"?

Is it a problem if the high-res raster is completely contained by the low-res raster?

Thanks for your help.

**Comment by ldesousa** [comment] 2018-04-02 17:14
Never seen this error before. That computation (`d_max`) is pretty straightforward, I suspect the problem is somewhere before, possibly with the computation of the region. Is there any possibility to get these two DEMs for testing?

Regarding the `far_edge`, try to leave by default for starters and then experiment by slowly increasing the value.

**Comment by iboates** [comment] 2018-04-03 16:03
The file is quite large so I had to put it on Google Drive: https://drive.google.com/file/d/1TFujNVZrqYuEsMiBaEYw7tnYhSz9-0Jx/view?usp=sharing

**Comment by ldesousa** [comment] 2018-04-08 08:06
The distance formula used in the `compute_d_max` method is wrong.

**Comment by ldesousa** [comment] 2018-04-08 16:35
@iboates I will now close this issue and submit a new version of `r.mblend` to the GRASS repository. In the meantime, you may download the blended raster (with default parameters) from here:
https://www.dropbox.com/s/w7wyr5z7ro4jabf/vp_merged.tif?dl=0

**Closed as completed** 2018-04-08 16:36 UTC

**Comment by iboates** [comment] 2018-04-11 07:57
Thanks @ldesousa, when do you think it will be live on the repo?

**Comment by ldesousa** [comment] 2018-04-11 17:29
@iboates I submitted the new version on Sunday, it should be available already. Can you try to re-install with `g.extension`?
